### Updates an existing patient entity
PUT http://localhost:4004/api/patients/503ef90a-2058-49f7-b48d-f9356f32b42c
Authorization: Bearer {{token}}
Content-Type: application/json

{
"name": "Viratkohli18",
"email": "ViratKohli1818@gmail.com",
"address": "RCB",
  "dateOfBirth": "1988-11-05"
}
